# Generated by Django 4.2.4 on 2023-09-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="classform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Faculty_In_Charge",
                    models.CharField(
                        blank=True,
                        choices=[],
                        max_length=120,
                        null=True,
                        verbose_name="Faculty In Charge",
                    ),
                ),
                (
                    "Number_of_Tut_Sections",
                    models.IntegerField(
                        blank=True, null=True, verbose_name=" Number of Tut Sections"
                    ),
                ),
                (
                    "Number_of_Lab_Sections",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Number of Lab Sections"
                    ),
                ),
                (
                    "Number_of_Lecture_Sections",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name=" Number of Lecture Sections",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="facultyForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Faculty_name",
                    models.CharField(
                        blank=True,
                        choices=[],
                        max_length=120,
                        null=True,
                        verbose_name="Faculty name",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="previewForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CDC_name", models.CharField(max_length=100)),
                ("Tut_number", models.CharField(max_length=100)),
                ("Lect_number", models.CharField(max_length=100)),
                ("Lab_number", models.CharField(max_length=100)),
                ("Faculty_List", models.CharField(max_length=100)),
            ],
        ),
    ]
