# Generated by Django 4.2.4 on 2023-10-03 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="classform",
            old_name="Number_of_Lecture_Sections",
            new_name="Number_of_Lec_Sections",
        ),
    ]
