# Generated by Django 4.2.4 on 2023-10-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "user",
            "0002_rename_number_of_lecture_sections_classform_number_of_lec_sections",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="classform",
            name="Faculty_In_Charge",
            field=models.CharField(
                blank=True,
                choices=[(0, "Faculty")],
                max_length=120,
                null=True,
                verbose_name="Faculty In Charge",
            ),
        ),
        migrations.AlterField(
            model_name="classform",
            name="Number_of_Tut_Sections",
            field=models.IntegerField(
                default=0, null=True, verbose_name=" Number of Tut Sections"
            ),
        ),
    ]
