# Generated by Django 4.2.4 on 2023-10-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_classform_number_of_tut_sections"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classform",
            name="Faculty_In_Charge",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "Faculty")],
                max_length=120,
                null=True,
                verbose_name="Faculty In Charge",
            ),
        ),
        migrations.AlterField(
            model_name="classform",
            name="Number_of_Lab_Sections",
            field=models.IntegerField(
                blank=True,
                choices=[(0, "0"), (10, "10"), (20, "20")],
                null=True,
                verbose_name="Number of Lab Sections",
            ),
        ),
        migrations.AlterField(
            model_name="classform",
            name="Number_of_Lec_Sections",
            field=models.IntegerField(
                blank=True,
                choices=[(0, "0"), (10, "10"), (20, "20")],
                null=True,
                verbose_name=" Number of Lecture Sections",
            ),
        ),
        migrations.AlterField(
            model_name="classform",
            name="Number_of_Tut_Sections",
            field=models.IntegerField(
                choices=[(0, "0"), (10, "10"), (20, "20")],
                null=True,
                verbose_name=" Number of Tut Sections",
            ),
        ),
    ]
