# Generated by Django 4.2.4 on 2023-10-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_alter_classform_faculty_in_charge_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classform",
            name="Faculty_In_Charge",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "Faculty")],
                null=True,
                verbose_name="Faculty In Charge",
            ),
        ),
        migrations.AlterField(
            model_name="classform",
            name="Number_of_Lab_Sections",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Number of Lab Sections"
            ),
        ),
        migrations.AlterField(
            model_name="classform",
            name="Number_of_Lec_Sections",
            field=models.IntegerField(
                blank=True, null=True, verbose_name=" Number of Lecture Sections"
            ),
        ),
        migrations.AlterField(
            model_name="classform",
            name="Number_of_Tut_Sections",
            field=models.IntegerField(
                null=True, verbose_name=" Number of Tut Sections"
            ),
        ),
    ]
