# Generated by Django 4.2.4 on 2023-11-01 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_listing_hd"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Listing_HD",
        ),
    ]
