# Generated by Django 4.2.4 on 2023-09-22 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="anouncement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=120, verbose_name="announcement_title"),
                ),
                ("date", models.DateTimeField(verbose_name="announcement_date")),
                ("description", models.TextField(blank=True)),
                ("handler", models.CharField(default="admin", max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="CDC_FD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CDC_ID", models.CharField(max_length=20, verbose_name="CDC_ID")),
                ("CDC_name", models.CharField(max_length=50, verbose_name="CDC_name")),
                (
                    "CDC_Department",
                    models.CharField(
                        choices=[
                            ("Chemical", "Chemical"),
                            ("Mechanical", "Mechanical"),
                            ("Electrical", "Electrical"),
                            ("Computer Science", "Computer Science"),
                            ("Physics", "Physics"),
                            ("Biology", "Biology"),
                            ("Chemistry", "Chemistry"),
                            ("Mathematics", "Mathematics"),
                        ],
                        max_length=100,
                        verbose_name="CDC_Department",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CDC_HD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CDC_HD_ID", models.CharField(max_length=20, verbose_name="CDC_ID")),
                (
                    "CDC_HD_name",
                    models.CharField(max_length=50, verbose_name="CDC_name"),
                ),
                (
                    "CDC_HD_Department",
                    models.CharField(
                        choices=[
                            ("Chemical", "Chemical"),
                            ("Mechanical", "Mechanical"),
                            ("Electrical", "Electrical"),
                            ("Computer Science", "Computer Science"),
                            ("Physics", "Physics"),
                            ("Biology", "Biology"),
                            ("Chemistry", "Chemistry"),
                            ("Mathematics", "Mathematics"),
                        ],
                        max_length=100,
                        verbose_name="CDC_Department",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Faculty_List",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                (
                    "Department",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Chemical", "Chemical"),
                            ("Mechanical", "Mechanical"),
                            ("Electrical", "Electrical"),
                            ("Computer Science", "Computer Science"),
                            ("Physics", "Physics"),
                            ("Biology", "Biology"),
                            ("Chemistry", "Chemistry"),
                            ("Mathematics", "Mathematics"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="department_description",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Department_name",
                    models.CharField(
                        choices=[
                            ("Chemical", "Chemical"),
                            ("Mechanical", "Mechanical"),
                            ("Electrical", "Electrical"),
                            ("Computer Science", "Computer Science"),
                            ("Physics", "Physics"),
                            ("Biology", "Biology"),
                            ("Chemistry", "Chemistry"),
                            ("Mathematics", "Mathematics"),
                        ],
                        max_length=50,
                        verbose_name="Department name",
                    ),
                ),
                (
                    "Department_Faculty",
                    models.ManyToManyField(blank=True, to="manager.faculty_list"),
                ),
                (
                    "Department_HOD",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
