# Generated by Django 4.2.4 on 2023-10-30 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0002_elective_fd_elective_hd"),
    ]

    operations = [
        migrations.RenameField(
            model_name="elective_fd",
            old_name="ELective_name",
            new_name="Elective_name",
        ),
    ]
