# Generated by Django 4.2.4 on 2023-11-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0003_rename_elective_name_elective_fd_elective_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="department_description",
            name="Department_Faculty",
        ),
        migrations.AlterField(
            model_name="cdc_fd",
            name="CDC_Department",
            field=models.CharField(
                choices=[
                    ("Chemical", "Chemical"),
                    ("Mechanical", "Mechanical"),
                    ("Electrical", "Electrical"),
                    ("Computer Science", "Computer Science"),
                    ("Physics", "Physics"),
                    ("Biology", "Biology"),
                    ("Chemistry", "Chemistry"),
                    ("Mathematics", "Mathematics"),
                    ("Economics", "Economics"),
                    ("Humanities", "Humanities"),
                ],
                max_length=100,
                verbose_name="CDC_Department",
            ),
        ),
        migrations.AlterField(
            model_name="cdc_hd",
            name="CDC_HD_Department",
            field=models.CharField(
                choices=[
                    ("Chemical", "Chemical"),
                    ("Mechanical", "Mechanical"),
                    ("Electrical", "Electrical"),
                    ("Computer Science", "Computer Science"),
                    ("Physics", "Physics"),
                    ("Biology", "Biology"),
                    ("Chemistry", "Chemistry"),
                    ("Mathematics", "Mathematics"),
                    ("Economics", "Economics"),
                    ("Humanities", "Humanities"),
                ],
                max_length=100,
                verbose_name="CDC_Department",
            ),
        ),
        migrations.AlterField(
            model_name="department_description",
            name="Department_name",
            field=models.CharField(
                choices=[
                    ("Chemical", "Chemical"),
                    ("Mechanical", "Mechanical"),
                    ("Electrical", "Electrical"),
                    ("Computer Science", "Computer Science"),
                    ("Physics", "Physics"),
                    ("Biology", "Biology"),
                    ("Chemistry", "Chemistry"),
                    ("Mathematics", "Mathematics"),
                    ("Economics", "Economics"),
                    ("Humanities", "Humanities"),
                ],
                max_length=50,
                verbose_name="Department name",
            ),
        ),
        migrations.AlterField(
            model_name="elective_fd",
            name="Elective_Department",
            field=models.CharField(
                choices=[
                    ("Chemical", "Chemical"),
                    ("Mechanical", "Mechanical"),
                    ("Electrical", "Electrical"),
                    ("Computer Science", "Computer Science"),
                    ("Physics", "Physics"),
                    ("Biology", "Biology"),
                    ("Chemistry", "Chemistry"),
                    ("Mathematics", "Mathematics"),
                    ("Economics", "Economics"),
                    ("Humanities", "Humanities"),
                ],
                max_length=100,
                verbose_name="Elective_Department",
            ),
        ),
        migrations.AlterField(
            model_name="elective_hd",
            name="Elective_HD_Department",
            field=models.CharField(
                choices=[
                    ("Chemical", "Chemical"),
                    ("Mechanical", "Mechanical"),
                    ("Electrical", "Electrical"),
                    ("Computer Science", "Computer Science"),
                    ("Physics", "Physics"),
                    ("Biology", "Biology"),
                    ("Chemistry", "Chemistry"),
                    ("Mathematics", "Mathematics"),
                    ("Economics", "Economics"),
                    ("Humanities", "Humanities"),
                ],
                max_length=100,
                verbose_name="Elective_Department",
            ),
        ),
        migrations.AlterField(
            model_name="faculty_list",
            name="Department",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Chemical", "Chemical"),
                    ("Mechanical", "Mechanical"),
                    ("Electrical", "Electrical"),
                    ("Computer Science", "Computer Science"),
                    ("Physics", "Physics"),
                    ("Biology", "Biology"),
                    ("Chemistry", "Chemistry"),
                    ("Mathematics", "Mathematics"),
                    ("Economics", "Economics"),
                    ("Humanities", "Humanities"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
