# Generated by Django 4.2.4 on 2023-11-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0004_remove_department_description_department_faculty_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cdc_fd",
            name="CDC_Department",
            field=models.CharField(
                choices=[
                    ("Chemical", "CHE"),
                    ("Mechanical", "MECH"),
                    ("Electrical", "EEE-INSTR"),
                    ("Computer Science", "Computer Science"),
                    ("Physics", "PHY"),
                    ("Biology", "BIO"),
                    ("Chemistry", "CHEM "),
                    ("Mathematics", "MATHS"),
                    ("Economics", "ECON & MGMT"),
                    ("Humanities", "HUM"),
                ],
                max_length=100,
                verbose_name="CDC_Department",
            ),
        ),
        migrations.AlterField(
            model_name="cdc_hd",
            name="CDC_HD_Department",
            field=models.CharField(
                choices=[
                    ("Chemical", "CHE"),
                    ("Mechanical", "MECH"),
                    ("Electrical", "EEE-INSTR"),
                    ("Computer Science", "Computer Science"),
                    ("Physics", "PHY"),
                    ("Biology", "BIO"),
                    ("Chemistry", "CHEM "),
                    ("Mathematics", "MATHS"),
                    ("Economics", "ECON & MGMT"),
                    ("Humanities", "HUM"),
                ],
                max_length=100,
                verbose_name="CDC_Department",
            ),
        ),
        migrations.AlterField(
            model_name="department_description",
            name="Department_name",
            field=models.CharField(
                choices=[
                    ("Chemical", "CHE"),
                    ("Mechanical", "MECH"),
                    ("Electrical", "EEE-INSTR"),
                    ("Computer Science", "Computer Science"),
                    ("Physics", "PHY"),
                    ("Biology", "BIO"),
                    ("Chemistry", "CHEM "),
                    ("Mathematics", "MATHS"),
                    ("Economics", "ECON & MGMT"),
                    ("Humanities", "HUM"),
                ],
                max_length=50,
                verbose_name="Department name",
            ),
        ),
        migrations.AlterField(
            model_name="elective_fd",
            name="Elective_Department",
            field=models.CharField(
                choices=[
                    ("Chemical", "CHE"),
                    ("Mechanical", "MECH"),
                    ("Electrical", "EEE-INSTR"),
                    ("Computer Science", "Computer Science"),
                    ("Physics", "PHY"),
                    ("Biology", "BIO"),
                    ("Chemistry", "CHEM "),
                    ("Mathematics", "MATHS"),
                    ("Economics", "ECON & MGMT"),
                    ("Humanities", "HUM"),
                ],
                max_length=100,
                verbose_name="Elective_Department",
            ),
        ),
        migrations.AlterField(
            model_name="elective_hd",
            name="Elective_HD_Department",
            field=models.CharField(
                choices=[
                    ("Chemical", "CHE"),
                    ("Mechanical", "MECH"),
                    ("Electrical", "EEE-INSTR"),
                    ("Computer Science", "Computer Science"),
                    ("Physics", "PHY"),
                    ("Biology", "BIO"),
                    ("Chemistry", "CHEM "),
                    ("Mathematics", "MATHS"),
                    ("Economics", "ECON & MGMT"),
                    ("Humanities", "HUM"),
                ],
                max_length=100,
                verbose_name="Elective_Department",
            ),
        ),
        migrations.AlterField(
            model_name="faculty_list",
            name="Department",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Chemical", "CHE"),
                    ("Mechanical", "MECH"),
                    ("Electrical", "EEE-INSTR"),
                    ("Computer Science", "Computer Science"),
                    ("Physics", "PHY"),
                    ("Biology", "BIO"),
                    ("Chemistry", "CHEM "),
                    ("Mathematics", "MATHS"),
                    ("Economics", "ECON & MGMT"),
                    ("Humanities", "HUM"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
