# Generated by Django 4.2.4 on 2023-11-18 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0007_department_description_upcoming_sem"),
    ]

    operations = [
        migrations.AddField(
            model_name="department_description",
            name="Previous_records",
            field=models.CharField(
                max_length=400, null=True, verbose_name="Link for the previous data"
            ),
        ),
    ]
