# Generated by Django 4.2.4 on 2023-11-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0008_department_description_previous_records"),
    ]

    operations = [
        migrations.AddField(
            model_name="department_description",
            name="Lock",
            field=models.BooleanField(default=False, verbose_name="Lock Website"),
        ),
    ]
