# Generated by Django 4.2.4 on 2023-11-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0009_department_description_lock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department_description",
            name="Previous_records",
            field=models.CharField(
                blank=True,
                max_length=400,
                null=True,
                verbose_name="Link for the previous data",
            ),
        ),
    ]
