# Generated by Django 4.2.9 on 2024-02-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0010_alter_department_description_previous_records"),
    ]

    operations = [
        migrations.AddField(
            model_name="department_description",
            name="Academic_year",
            field=models.CharField(
                choices=[("Sem 1", "Sem 1"), ("Sem 2", "Sem 2")],
                max_length=50,
                null=True,
                verbose_name="Upcoming Semester",
            ),
        ),
        migrations.AlterField(
            model_name="department_description",
            name="Upcoming_Sem",
            field=models.CharField(
                choices=[
                    (0, "2023-2024"),
                    (1, "2022-2023"),
                    (2, "2021-2022"),
                    (3, "2020-2021"),
                    (4, "2019-2020"),
                    (5, "2018-2019"),
                    (6, "2017-2018"),
                    (7, "2016-2017"),
                    (8, "2015-2016"),
                    (9, "2014-2015"),
                ],
                max_length=50,
                null=True,
                verbose_name="Academic Year",
            ),
        ),
    ]
