# Generated by Django 4.2.9 on 2024-03-18 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0013_alter_department_description_academic_year_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PHD_List",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("PNR_No", models.CharField(max_length=50)),
                (
                    "Department",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CHE", "Chemical"),
                            ("MECH", "Mechanical"),
                            ("EEE-INSTR", "Electrical"),
                            ("Computer Science", "Computer Science"),
                            ("PHY", "Physics"),
                            ("BIO", "Biology"),
                            ("CHEM", "Chemistry"),
                            ("MATHS", "Mathematics"),
                            ("ECON & MGMT", "Economics"),
                            ("HUM", "Humanities"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="faculty_list",
            old_name="last_name",
            new_name="ID_No",
        ),
    ]
