# Generated by Django 4.2.9 on 2024-03-18 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0014_phd_list_rename_last_name_faculty_list_id_no"),
    ]

    operations = [
        migrations.RenameField(
            model_name="phd_list",
            old_name="PNR_No",
            new_name="PSM_No",
        ),
    ]
