# Generated by Django 4.2.9 on 2024-03-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0016_cdc_fd_upcoming_sem_fd_cdc_hd_upcoming_sem_hd_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WILP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "WILP_ID",
                    models.CharField(max_length=20, verbose_name="Elective_ID"),
                ),
                (
                    "WILP_name",
                    models.CharField(max_length=50, verbose_name="Elective_name"),
                ),
                (
                    "WILP_Department",
                    models.CharField(
                        choices=[
                            ("CHE", "Chemical"),
                            ("MECH", "Mechanical"),
                            ("EEE-INSTR", "Electrical"),
                            ("Computer Science", "Computer Science"),
                            ("PHY", "Physics"),
                            ("BIO", "Biology"),
                            ("CHEM", "Chemistry"),
                            ("MATHS", "Mathematics"),
                            ("ECON & MGMT", "Economics"),
                            ("HUM", "Humanities"),
                        ],
                        max_length=100,
                        verbose_name="Elective_Department",
                    ),
                ),
                (
                    "Upcoming_SEM_WILP",
                    models.CharField(
                        choices=[("Sem 1", "Sem 1"), ("Sem 2", "Sem 2")],
                        max_length=50,
                        null=True,
                        verbose_name="Upcoming Semester",
                    ),
                ),
            ],
        ),
    ]
