# Generated by Django 4.2.9 on 2024-03-19 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0017_wilp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="elective_fd",
            name="Upcoming_Sem_El_FD",
        ),
        migrations.RemoveField(
            model_name="elective_hd",
            name="Upcoming_Sem_El_HD",
        ),
        migrations.RemoveField(
            model_name="wilp",
            name="Upcoming_SEM_WILP",
        ),
    ]
