# Generated by Django 4.2.9 on 2024-03-23 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0018_remove_elective_fd_upcoming_sem_el_fd_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cdc_fd",
            name="CDC_Department",
            field=models.CharField(
                choices=[
                    ("CHE", "Chemical"),
                    ("MECH", "Mechanical"),
                    ("EEE", "Electrical"),
                    ("Computer Science", "Computer Science"),
                    ("PHY", "Physics"),
                    ("BIO", "Biology"),
                    ("CHEM", "Chemistry"),
                    ("MATH", "Mathematics"),
                    ("ECON", "Economics"),
                    ("HUM", "Humanities"),
                ],
                max_length=100,
                verbose_name="CDC_Department",
            ),
        ),
        migrations.AlterField(
            model_name="cdc_hd",
            name="CDC_HD_Department",
            field=models.CharField(
                choices=[
                    ("CHE", "Chemical"),
                    ("MECH", "Mechanical"),
                    ("EEE", "Electrical"),
                    ("Computer Science", "Computer Science"),
                    ("PHY", "Physics"),
                    ("BIO", "Biology"),
                    ("CHEM", "Chemistry"),
                    ("MATH", "Mathematics"),
                    ("ECON", "Economics"),
                    ("HUM", "Humanities"),
                ],
                max_length=100,
                verbose_name="CDC_Department",
            ),
        ),
        migrations.AlterField(
            model_name="department_description",
            name="Department_name",
            field=models.CharField(
                choices=[
                    ("CHE", "Chemical"),
                    ("MECH", "Mechanical"),
                    ("EEE", "Electrical"),
                    ("Computer Science", "Computer Science"),
                    ("PHY", "Physics"),
                    ("BIO", "Biology"),
                    ("CHEM", "Chemistry"),
                    ("MATH", "Mathematics"),
                    ("ECON", "Economics"),
                    ("HUM", "Humanities"),
                ],
                max_length=50,
                verbose_name="Department name",
            ),
        ),
        migrations.AlterField(
            model_name="elective_fd",
            name="Elective_Department",
            field=models.CharField(
                choices=[
                    ("CHE", "Chemical"),
                    ("MECH", "Mechanical"),
                    ("EEE", "Electrical"),
                    ("Computer Science", "Computer Science"),
                    ("PHY", "Physics"),
                    ("BIO", "Biology"),
                    ("CHEM", "Chemistry"),
                    ("MATH", "Mathematics"),
                    ("ECON", "Economics"),
                    ("HUM", "Humanities"),
                ],
                max_length=100,
                verbose_name="Elective_Department",
            ),
        ),
        migrations.AlterField(
            model_name="elective_hd",
            name="Elective_HD_Department",
            field=models.CharField(
                choices=[
                    ("CHE", "Chemical"),
                    ("MECH", "Mechanical"),
                    ("EEE", "Electrical"),
                    ("Computer Science", "Computer Science"),
                    ("PHY", "Physics"),
                    ("BIO", "Biology"),
                    ("CHEM", "Chemistry"),
                    ("MATH", "Mathematics"),
                    ("ECON", "Economics"),
                    ("HUM", "Humanities"),
                ],
                max_length=100,
                verbose_name="Elective_Department",
            ),
        ),
        migrations.AlterField(
            model_name="faculty_list",
            name="Department",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CHE", "Chemical"),
                    ("MECH", "Mechanical"),
                    ("EEE", "Electrical"),
                    ("Computer Science", "Computer Science"),
                    ("PHY", "Physics"),
                    ("BIO", "Biology"),
                    ("CHEM", "Chemistry"),
                    ("MATH", "Mathematics"),
                    ("ECON", "Economics"),
                    ("HUM", "Humanities"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="phd_list",
            name="Department",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CHE", "Chemical"),
                    ("MECH", "Mechanical"),
                    ("EEE", "Electrical"),
                    ("Computer Science", "Computer Science"),
                    ("PHY", "Physics"),
                    ("BIO", "Biology"),
                    ("CHEM", "Chemistry"),
                    ("MATH", "Mathematics"),
                    ("ECON", "Economics"),
                    ("HUM", "Humanities"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="wilp",
            name="WILP_Department",
            field=models.CharField(
                choices=[
                    ("CHE", "Chemical"),
                    ("MECH", "Mechanical"),
                    ("EEE", "Electrical"),
                    ("Computer Science", "Computer Science"),
                    ("PHY", "Physics"),
                    ("BIO", "Biology"),
                    ("CHEM", "Chemistry"),
                    ("MATH", "Mathematics"),
                    ("ECON", "Economics"),
                    ("HUM", "Humanities"),
                ],
                max_length=100,
                verbose_name="Elective_Department",
            ),
        ),
    ]
