# Generated by Django 4.2.9 on 2024-03-23 05:19

from django.db import migrations, models
import django.db.models.deletion
import manager.models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0019_alter_cdc_fd_cdc_department_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.CharField(
                        choices=[
                            ("2023-2024", "2023-2024"),
                            ("2022-2023", "2022-2023"),
                            ("2021-2022", "2021-2022"),
                            ("2020-2021", "2020-2021"),
                            ("2019-2020", "2019-2020"),
                            ("2018-2019", "2018-2019"),
                            ("2017-2018", "2017-2018"),
                            ("2016-2017", "2016-2017"),
                            ("2015-2016", "2015-2016"),
                            ("2014-2015", "2014-2015"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="Academic Year",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("CHE", "Chemical"),
                            ("MECH", "Mechanical"),
                            ("EEE", "Electrical"),
                            ("Computer Science", "Computer Science"),
                            ("PHY", "Physics"),
                            ("BIO", "Biology"),
                            ("CHEM", "Chemistry"),
                            ("MATH", "Mathematics"),
                            ("ECON", "Economics"),
                            ("HUM", "Humanities"),
                        ],
                        max_length=50,
                        verbose_name="Department name",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Semester",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[("Sem 1", "Sem 1"), ("Sem 2", "Sem 2")],
                        max_length=50,
                        null=True,
                        verbose_name="Upcoming Semester",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Upload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to=manager.models.dynamic_upload_path),
                ),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="manager.academicyear",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="manager.department",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="manager.semester",
                    ),
                ),
            ],
        ),
    ]
