# Generated by Django 4.2.9 on 2024-03-25 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0020_academicyear_department_semester_upload"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Upload",
            new_name="Files",
        ),
    ]
