# Generated by Django 4.2.9 on 2024-03-25 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0021_rename_upload_files"),
    ]

    operations = [
        migrations.AlterField(
            model_name="files",
            name="academic_year",
            field=models.CharField(
                choices=[
                    ("2023-2024", "2023-2024"),
                    ("2022-2023", "2022-2023"),
                    ("2021-2022", "2021-2022"),
                    ("2020-2021", "2020-2021"),
                    ("2019-2020", "2019-2020"),
                    ("2018-2019", "2018-2019"),
                    ("2017-2018", "2017-2018"),
                    ("2016-2017", "2016-2017"),
                    ("2015-2016", "2015-2016"),
                    ("2014-2015", "2014-2015"),
                ],
                max_length=50,
                null=True,
                verbose_name="Academic Year",
            ),
        ),
        migrations.AlterField(
            model_name="files",
            name="department",
            field=models.CharField(
                choices=[
                    ("CHE", "Chemical"),
                    ("MECH", "Mechanical"),
                    ("EEE", "Electrical"),
                    ("Computer Science", "Computer Science"),
                    ("PHY", "Physics"),
                    ("BIO", "Biology"),
                    ("CHEM", "Chemistry"),
                    ("MATH", "Mathematics"),
                    ("ECON", "Economics"),
                    ("HUM", "Humanities"),
                ],
                max_length=50,
                verbose_name="Department name",
            ),
        ),
        migrations.AlterField(
            model_name="files",
            name="semester",
            field=models.CharField(
                choices=[("Sem 1", "Sem 1"), ("Sem 2", "Sem 2")],
                max_length=50,
                null=True,
                verbose_name="Upcoming Semester",
            ),
        ),
        migrations.DeleteModel(
            name="AcademicYear",
        ),
        migrations.DeleteModel(
            name="Department",
        ),
        migrations.DeleteModel(
            name="Semester",
        ),
    ]
