# Generated by Django 4.2.9 on 2024-03-25 04:48

from django.db import migrations, models
import manager.models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0022_alter_files_academic_year_alter_files_department_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cachefile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=manager.models.dynamic_upload_path_cache
                    ),
                ),
            ],
        ),
    ]
