# Generated by Django 4.2.9 on 2024-03-26 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0024_alter_cdc_fd_cdc_department_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faculty_list",
            name="Department",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="manager.department_description",
            ),
        ),
        migrations.AlterField(
            model_name="phd_list",
            name="Department",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="manager.department_description",
            ),
        ),
    ]
