# Generated by Django 4.2.9 on 2024-03-26 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0025_alter_faculty_list_department_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faculty_list",
            name="Department",
            field=models.CharField(
                choices=[
                    ("CHE", "Chemical"),
                    ("MECH ", "Mechanical"),
                    ("EEE", "Electrical"),
                    ("Computer Science", " Computer Science"),
                    ("PHY", " Physics"),
                    ("BIO", " Biology"),
                    ("CHEM", "Chemistry"),
                    ("MATH", "Mathematics"),
                    ("ECON", "Economics"),
                    ("HUM", "Humanities"),
                ],
                max_length=50,
                verbose_name="Department name",
            ),
        ),
        migrations.AlterField(
            model_name="phd_list",
            name="Department",
            field=models.CharField(
                choices=[
                    ("CHE", "Chemical"),
                    ("MECH ", "Mechanical"),
                    ("EEE", "Electrical"),
                    ("Computer Science", " Computer Science"),
                    ("PHY", " Physics"),
                    ("BIO", " Biology"),
                    ("CHEM", "Chemistry"),
                    ("MATH", "Mathematics"),
                    ("ECON", "Economics"),
                    ("HUM", "Humanities"),
                ],
                max_length=50,
                verbose_name="Department name",
            ),
        ),
    ]
