# Generated by Django 4.2.9 on 2024-04-10 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0028_alter_cdc_fd_options_alter_cdc_hd_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="files",
            name="semester",
            field=models.CharField(
                choices=[("Sem 1", "Sem 1"), ("Sem 2", "Sem 2")],
                max_length=50,
                null=True,
                verbose_name="Semester",
            ),
        ),
    ]
