# Generated by Django 5.0.4 on 2024-07-15 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0029_alter_files_semester'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cdc_fd',
            options={'ordering': ['CDC_name'], 'verbose_name': 'FD CDC', 'verbose_name_plural': 'FD CDC'},
        ),
        migrations.AlterModelOptions(
            name='cdc_hd',
            options={'ordering': ['CDC_HD_name'], 'verbose_name': 'HD CDC', 'verbose_name_plural': 'HD CDC'},
        ),
        migrations.AlterModelOptions(
            name='elective_fd',
            options={'ordering': ['Elective_name'], 'verbose_name': 'FD Eectives', 'verbose_name_plural': 'FD Electives'},
        ),
        migrations.AlterModelOptions(
            name='elective_hd',
            options={'ordering': ['Elective_HD_name'], 'verbose_name': 'HD ELectives', 'verbose_name_plural': 'HD Electives'},
        ),
        migrations.AlterModelOptions(
            name='files',
            options={'verbose_name': 'Previous Files', 'verbose_name_plural': 'Previous Files'},
        ),
        migrations.AlterModelOptions(
            name='wilp',
            options={'ordering': ['WILP_name'], 'verbose_name': 'WILP', 'verbose_name_plural': 'WILP'},
        ),
    ]
